name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags: "*"

permissions:
  actions: write
  contents: read

jobs:
  tests:
    name: Tests - Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
          # For some reason GLFW won't let us create a window on 32 bit ubuntu
          # - x86
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v3
      - name: Set the number of threads for the tests
        run: |
          echo "JULIA_NUM_THREADS=5,5" >> "$GITHUB_ENV"
      - uses: julia-actions/julia-runtest@v1
        with:
          prefix: xvfb-run -a -s '-screen 0 1024x768x24'
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v7
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
      - uses: julia-actions/cache@v3
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          DISPLAY: :99
